version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskmanager_app
    container_name: php_app_container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    depends_on:
      - db
      - node
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: olga
      MYSQL_PASSWORD: password123
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  node:
    image: node:16
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
